apiVersion: v1
kind: Secret
metadata:
  name: idp-ingress-tls
  labels:
    app: idp-app
data:
  tls.crt: repl{{ ConfigOption "tls_cert" | b64enc }}
  tls.key: repl{{ ConfigOption "tls_key" | b64enc }}
type: kubernetes.io/tls